// <auto-generated />
namespace ToDoList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addNotNullToDueDateAndDescription_ToDoTask_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNotNullToDueDateAndDescription_ToDoTask_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "202308292125560_addNotNullToDueDateAndDescription_ToDoTask_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
